use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'



target 'AHFMEpisodeListVCManager_Example' do
  pod 'AHFMEpisodeListVCManager', :path => '../'

  target 'AHFMEpisodeListVCManager_Tests' do
    inherit! :search_paths

    
  end
end
